### ISSUE TITLE
Refactor v1 Telegram Bot into 3 layers

### ISSUE THREAD

**Issue by geodome** [suss-swe-ig/suss-telegram-groups#1]
![architecture](https://github.com/user-attachments/assets/78a0ab60-2026-4eb9-91fb-abe6c9058b3b)

The Service Layer is responsible for handling interactions with the Telegram API Server. The SingletonService class interacts with the Telegram API Server via the AsyncTelebot class. The logger class will stream logs to a Telegram Channel or chat group.

The Busines Logic Layer consists of Admin Class and User class that provides authentication and authorisation for specific commands. These 2 classes also execute the logic of these commands. The Business Layer will manipulate TelegramGroup objects created by the Data Persistence Layer.

The Data Persistence Layer provides the SingletonDatabase class that reads and write the underlying data store powered by the Python Shelve module.

**Comment by suss-swe-ig** [comment]
refactor branch has been merged into main and forked as v2.
