### ISSUE TITLE
Allow user to download course information pdf

### ISSUE THREAD

**Issue by sheppy9** [suss-swe-ig/suss-telegram-groups#10]
Allow user to request for the course information, the bot should download from the following URL and send it to the group.

The Course code can obtain from the group name itself (which also mean the group name have to be strictly in certain format)

Example Link to download

https://sims1.suss.edu.sg/ESERVICE/Public/ViewCourse/ViewCourse.aspx?crsecd=ICT246&viewtype=pdf&isft=0
https://sims1.suss.edu.sg/ESERVICE/Public/ViewCourse/ViewCourse.aspx?crsecd=ICT335&viewtype=pdf&isft=0

**Comment by geodome** [comment]
I will split this issue into 2 smaller issues and then assign them to you.

**Comment by geodome** [comment]
https://github.com/suss-swe-ig/suss-telegram-groups/issues/14

https://github.com/suss-swe-ig/suss-telegram-groups/issues/15

**Comment by geodome** [comment]
This issue is too big, so it is split into 2 issues:

- https://github.com/suss-swe-ig/suss-telegram-groups/issues/14

- https://github.com/suss-swe-ig/suss-telegram-groups/issues/15
